kind: ConfigMap
metadata:
  name: argocd-cm
apiVersion: v1
data:
  url: https://argocd.baloise.dev
  users.anonymous.enabled: 'true'
  statusbadge.enabled: 'true'
  admin.enabled: 'false'
  resource.exclusions: |
    - apiGroups:
      - tekton.dev
      kinds:
      - PipelineRun
      clusters:
      - https://kubernetes.default.svc
  resource.customizations: |
    tekton.dev/PipelineRun:
      ignoreDifferences: |
        jsonPointers:
        - /

  repositories: |
    - type: helm
      url: https://registry.baloise.dev/chartrepo/library
      name: incubator-library
    - type: helm
      url: https://charts.bitnami.com/bitnami
      name: bitnami
  dex.config:
    connectors:
    - type: github
      # Required field for connector id.
      id: github
      # Required field for connector name.
      name: GitHub
      config:
        # Credentials can be string literals or pulled from the environment.
        clientID: istrau2
        clientSecret: $dex.clientSecret
        redirectURI: http://127.0.0.1:5556/dex/callback
        orgs:
        - name: my-organization
          # Include all teams as claims.
        - name: my-organization-with-teams
          # A white list of teams. Only include group claims for these teams.
          teams:
          - red-team
          - blue-team
        # Flag which indicates that all user groups and teams should be loaded.
        loadAllGroups: false
