apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # namespaces
  - namespaces/ingress-nginx.yaml
  - namespaces/sealed-secrets.yaml
  # - namespaces/argocd.yaml
  # projects
  - projects/default.yaml
  # applications
  - apps/ingress-nginx.yaml
  - apps/sealed-secrets.yaml
  - apps/argocd.yaml
