apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - github.com/argoproj/argo-cd/manifests/install?ref=3d1f37b0c53f4c75864dc7339e2831c6e6a947e0

resources:
  - namespace.yaml
  - ingress.yaml
#   - base/argocd-sealed-secret.yaml
#   - base/default-appprojects.yaml
#   - base/servicemonitors.yaml

patchesStrategicMerge:
  - patch/configmap.yaml
#   - overlays/argocd-dex-server.yaml
#   - overlays/argocd-dex-server-sa.yaml
#   - overlays/argocd-rbac-cm.yaml
#   - overlays/argocd-redis.yaml
#   - overlays/argocd-redis-ha-haproxy.yaml
#   - overlays/argocd-server-deploy.yaml
#   - overlays/argocd-repo-server-deploy.yaml
