apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  # v1.6.2
  - github.com/argoproj/argo-cd/manifests/cluster-install?ref=3d1f37b0c53f4c75864dc7339e2831c6e6a947e0

resources:
  - namespace.yaml
  - ingress.yaml

patchesStrategicMerge:
  - configmap.patch.yaml
