apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: sealed-secrets

resources:
  - https://github.com/jetstack/cert-manager/releases/download/v0.16.1/cert-manager.yaml
  - clusterissuer.yaml