apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: sealed-secrets
  source:
    repoURL: git@github.com:entropy-fund/gitops-dev.git
    targetRevision: HEAD
    path: sealed-secrets
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
