apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-repo-server
spec:
  replicas: 3
  template:
    spec:
      affinity: null
      containers:
        - name: argocd-repo-server
          env:
            - name: ARGOCD_GPG_ENABLED
              value: "false"
#    spec:
#      containers:
#        - image: 'niiku/argocd:latest'
#          name: argocd-repo-server
